import { Utensils, Shirt, Wrench, HeartPulse, GraduationCap, Home, Car, Music, Calendar } from "lucide-react";

export const CATEGORIES = [
    {
        id: "food",
        name: "Food & Cafes",
        icon: Utensils,
        description: "Restaurants, Cafes, Bakeries & Street Food",
        image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=2070",
        subCategories: ["Veg/Non-Veg", "Cafe", "Bakery", "Street Food", "Cloud Kitchen"],
        count: 156
    },
    {
        id: "fashion",
        name: "Fashion & Clothing",
        icon: Shirt,
        description: "Men's, Women's, Ethnic & Accessories",
        image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=2070",
        subCategories: ["Men's Wear", "Women's Wear", "Ethnic", "Footwear", "Accessories"],
        count: 89
    },
    {
        id: "services",
        name: "Local Services",
        icon: Wrench,
        description: "Salons, Repairs, Mechanics & Cleaning",
        image: "https://images.unsplash.com/photo-1581578017093-cd30fce4eeb7?q=80&w=2070",
        subCategories: ["Salons", "Repair", "Car Service", "Tailors", "Cleaning"],
        count: 64
    },
    {
        id: "health",
        name: "Health & Wellness",
        icon: HeartPulse,
        description: "Clinics, Gyms, Labs & Pharmacies",
        image: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?q=80&w=2089",
        subCategories: ["Clinics", "Labs", "Pharmacy", "Gyms", "Yoga"],
        count: 42
    },
    {
        id: "education",
        name: "Education & Training",
        icon: GraduationCap,
        description: "Coaching, Tuition, Skills & Arts",
        image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=2070",
        subCategories: ["Coaching", "Tuition", "Skills", "Computer", "Music/Dance"],
        count: 35
    },
    {
        id: "realestate",
        name: "Real Estate",
        icon: Home,
        description: "PGs, Rentals, Commercial & Agents",
        image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=2073",
        subCategories: ["PG & Hostels", "Rentals", "Commercial", "Agents", "Co-working"],
        count: 28
    },
    {
        id: "automotive",
        name: "Automotive",
        icon: Car,
        description: "Showrooms, Accessories, Wash & Detailing",
        image: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?q=80&w=2074",
        subCategories: ["Showrooms", "Accessories", "Car Wash", "Detailing", "Mechanics"],
        count: 19
    },
    {
        id: "entertainment",
        name: "Entertainment",
        icon: Music,
        description: "Gaming, Theaters, Parks & Nightlife",
        image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=2070",
        subCategories: ["Gaming Zones", "Theaters", "Theme Parks", "Clubs", "Lounges"],
        count: 45
    },
    {
        id: "events",
        name: "Events & Weddings",
        icon: Calendar,
        description: "Venues, Planners, Decorators & Catering",
        image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=2069",
        subCategories: ["Venues", "Planners", "Decor", "Catering", "Photography"],
        count: 31
    }
];

export const SPOTS = [
    {
        id: 1,
        name: "The Cloud Lounge",
        category: "Entertainment",
        rating: 4.9,
        image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=2070",
        location: "Downtown Skyline",
        tags: ["Rooftop", "Cocktails"],
        price: "$$$",
        distance: 2.5,
    },
    {
        id: 2,
        name: "Sakura Fusion",
        category: "Food & Cafes",
        rating: 4.8,
        image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=2070",
        location: "Arts District",
        tags: ["Sushi", "Modern"],
        price: "$$$$",
        distance: 3.2,
    },
    {
        id: 3,
        name: "Neon Arcade",
        category: "Entertainment",
        rating: 4.7,
        image: "https://images.unsplash.com/photo-1534270804882-6b5048b1c1fc?q=80&w=2012",
        location: "Retro Row",
        tags: ["Games", "Bar"],
        price: "$$",
        distance: 1.8,
    },
    {
        id: 4,
        name: "Brew & Bean",
        category: "Food & Cafes",
        rating: 4.6,
        image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=2574",
        location: "University Ave",
        tags: ["Coffee", "Study"],
        price: "$",
        distance: 0.8,
    },
    {
        id: 5,
        name: "Urban Garden",
        category: "Local Services",
        rating: 4.9,
        image: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?q=80&w=2600",
        location: "City Park",
        tags: ["Walk", "Relax"],
        price: "$",
        distance: 1.2,
    },
    {
        id: 6,
        name: "The Velvet Room",
        category: "Entertainment",
        rating: 4.5,
        image: "https://images.unsplash.com/photo-1566417713204-01998813ee47?q=80&w=2672",
        location: "Historic District",
        tags: ["Jazz", "Live Music"],
        price: "$$$",
        distance: 4.1,
    },
    {
        id: 7,
        name: "Luxe Autos",
        category: "Automotive",
        rating: 4.8,
        image: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?q=80&w=2074",
        location: "Auto Mall",
        tags: ["Showroom", "Luxury"],
        price: "$$$$",
        distance: 5.7,
    },
    {
        id: 8,
        name: "Elite Realty",
        category: "Real Estate",
        rating: 4.7,
        image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=2073",
        location: "Business Hub",
        tags: ["Office", "Commercial"],
        price: "$$$",
        distance: 3.9,
    },
    {
        id: 9,
        name: "FitZone Pro",
        category: "Health & Wellness",
        rating: 4.6,
        image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=2070",
        location: "Health Park",
        tags: ["Gym", "Crossfit"],
        price: "$$",
        distance: 2.3,
    },
    {
        id: 10,
        name: "Style Studio",
        category: "Fashion & Clothing",
        rating: 4.8,
        image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=2070",
        location: "Fashion Street",
        tags: ["Boutique", "Trendy"],
        price: "$$$",
        distance: 1.5,
    },
];
