#!/usr/bin/env node

console.log('\n🎯 SPOTLY Backend Setup - Interactive Guide\n');
console.log('='.repeat(50));
console.log('\n📋 STEP 1: MongoDB Atlas Setup\n');
console.log('1. Open your browser and go to:');
console.log('   👉 https://www.mongodb.com/cloud/atlas/register\n');
console.log('2. Sign up (use Google for fastest signup)\n');
console.log('3. Create a FREE cluster (M0 tier)');
console.log('   - Provider: AWS');
console.log('   - Region: Choose closest to you\n');
console.log('4. Create Database User:');
console.log('   - Username: spotly');
console.log('   - Password: Click "Autogenerate" and COPY IT!\n');
console.log('5. Network Access:');
console.log('   - Add IP: 0.0.0.0/0 (allow from anywhere)\n');
console.log('6. Get Connection String:');
console.log('   - Click "Connect" → "Drivers"');
console.log('   - Copy the connection string\n');
console.log('='.repeat(50));
console.log('\n📝 STEP 2: Update .env File\n');
console.log('Your connection string looks like:');
console.log('mongodb+srv://spotly:<password>@cluster0.xxxxx.mongodb.net/?retryWrites=true&w=majority\n');
console.log('Replace <password> with your actual password and add /spotly before the ?:\n');
console.log('Example:');
console.log('mongodb+srv://spotly:MyPass123@cluster0.abc.mongodb.net/spotly?retryWrites=true&w=majority\n');
console.log('='.repeat(50));
console.log('\n✅ Once you have your connection string:\n');
console.log('1. Open: BACKEND\\.env');
console.log('2. Update the MONGODB_URI line');
console.log('3. Save the file\n');
console.log('='.repeat(50));
console.log('\n🚀 STEP 3: Run These Commands\n');
console.log('In BACKEND folder:');
console.log('  npm run seed    # Seed the database');
console.log('  npm run dev     # Start backend server\n');
console.log('In frontend folder (new terminal):');
console.log('  npm run dev     # Start frontend\n');
console.log('='.repeat(50));
console.log('\n🎉 Then visit: http://localhost:3000\n');
console.log('Login with: admin@spotly.com / admin123\n');
console.log('='.repeat(50));
console.log('\n💡 Need help? Check BACKEND/MONGODB_SETUP.md\n');
